# Generated by Django 3.0.6 on 2020-05-14 12:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('author_info', models.CharField(max_length=200)),
                ('author_slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_outcome', models.CharField(max_length=200)),
                ('course_slug', models.SlugField(max_length=200)),
                ('course_credit', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('department_slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=200)),
                ('topic_content', models.TextField()),
                ('topic_slug', models.SlugField(max_length=200)),
                ('topic_published', models.DateTimeField(default=datetime.datetime(2020, 5, 14, 12, 32, 48, 318985), verbose_name='date published')),
                ('topic_summary', models.CharField(max_length=200)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app1_db.Author', verbose_name='author')),
                ('course_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app1_db.Course', verbose_name='course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app1_db.Department', verbose_name='department'),
        ),
        migrations.AddField(
            model_name='author',
            name='course_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app1_db.Course', verbose_name='course'),
        ),
        migrations.AddField(
            model_name='author',
            name='department_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app1_db.Department', verbose_name='department'),
        ),
    ]
