# Generated by Django 3.0.6 on 2020-05-14 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='author',
            new_name='author_name',
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 23, 21, 11, 913097), verbose_name='date published'),
        ),
    ]
